### ISSUE TITLE
Update packages architecture?

### ISSUE THREAD

**Issue by roll** [okfn/datapackage-sql-py#4]
### Current

After **Tabular Storage** concept introduction having high-level interfaces for every backend is not required. All backend related code are encapsulated in `Storage` implementations: 

![](https://github.com/okfn/jsontableschema-bigquery-py/raw/master/diagram.png)

So for now high-level code for the integrations on the datapackage level is just the same (copy-past).
### Proposed

So proposed packages architecture is to have:
#### Drivers

```
jsontableschema-bigquery-py
jsontableschema-sql-py
jsontableschema-*-py
```

`Storage` class implementations.
Having no deal with filesystem operations etc.
#### High-level interface (resource level)

```
jsontableschema-storage-py
```

High-level interface for the resource (schema+data) level.
Import/export + ... + `Storage` class interface for the reference.
#### High-level interface (datapackage level)

```
datapackage-storage-py
```

High-level interface for the datapackage level.
Import/export + ... + all high-level tests for the different real world datapackages and backends.
This repository and tests could be a "checksum" for all the packages in the stack:
- tabulator-py
- jsontableschema-py
- datapackage-py
- jsontableschema-*-py
- etc

**Comment by roll** [comment]
@vitorbaptista 
What do you thinks about the topic?

@pwalsh had an idea to have `Storage` ABCMeta interface and this code - https://github.com/okfn/jsontableschema-bigquery-py/blob/master/jtsbq/resource.py (just around 50 lines) as part of `jsontableschema-py` package (because it's really coupled).

Thinking by analogy all `datapackage-bigquery-py` and `datapackage-sql-py` (it's another 75 unique lines) could be merged as part of `datapackage-py`.

It's possible because interface of `Storage` and their implementations (sql etc) are strongly divided.

I have not preferences between merging or having `*-storage-py` packages.

**Comment by pwalsh** [comment]
@roll ( cc @vitorbaptista  ) I'm happy to have boilerplate Storage and connector classes and functions in those base libs, yes, on the assumption that it makes writing connectors to new storages (SQL + BigQuery now, Mongo, Cassandra, etc etc next) simpler and more DRY.

**Comment by roll** [comment]
Yea it could be much easier to maintain (reducing number of packages) and document how to write a `Storage`.

Also for the end-user could be cool to have something like (all flow could be documented in facade package):

```
import datapackage

dp = datapackage.DataPackage()
dp.metadata['name'] = 'my_sleep_duration'
dp.metadata['resources'] = [
    {'name': 'data'}
]
resource.metadata['data'] = [
    7, 8, 5, 6, 9, 7, 8
]
dp.export_package(<storage:sql/bq/etc>)
```

**Comment by roll** [comment]
FIXED
https://github.com/okfn/datapackage-storage-py
