### ISSUE TITLE
The exported datapackage is invalid

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-sql-py#8]
The minimum a datapackage needs to be valid is a `name` attribute. As we're not storing the metadata (see #5), we don't have the original datapackage's name. It might not even exist, when we're simply exporting a table that was never a datapackage.

That being the case, we either need to have some default name, or require one on the `export_package()` call.

**Comment by roll** [comment]
I think 

```
def export_package(storage, descriptor, name='some-default'):
```

could be nice.

**Comment by vitorbaptista** [comment]
@roll I've commited this directly into master, because it was blocking me. Please, when you have some time, review my changes at https://github.com/okfn/datapackage-sql-py/commit/32261138c4c436eb46ed38c1bfdc63bffd8a9a72. If you find any problem, reopen this issue.

I haven't added a default name because it self like something the user must decide by herself.

**Comment by roll** [comment]
Thanks @vitorbaptista if we'll add storing metadata we could make it optional in a future.

**Comment by vitorbaptista** [comment]
:+1:
